export const SET_LOADING = 'SET_LOADING';
export const GET_LIST_PRODUCTS_SUCCESS = 'GET_LIST_PRODUCTS_SUCCESS';
export const GET_LIST_PRODUCTS_SAGA = 'GET_LIST_PRODUCTS_SAGA'
export const GET_LIST_PRODUCTS_ERROR = 'GET_LIST_PRODUCTS_ERROR';

export const SET_PAGINATIONS = 'SET_PAGINATIONS'

// filter nè
export const SET_FILTER = 'SET_FILTER'

// clear filter
export const CLEAR_FILTER_SAGA = 'CLEAR_FILTER_SAGA'
export const SET_CLEAR_FILTER = 'SET_CLEAR_FILTER'

// brands nè
export const GET_LIST_ALL_BRANDS_SUCCESS = 'GET_LIST_ALL_BRANDS_SUCCESS'
export const GET_LIST_ALL_BRANDS_ERROR = 'GET_LIST_ALL_BRANDS_ERROR'
export const GET_LIST_BRANDS_SAGA = 'GET_LIST_BRANDS_SAGA'
export const GET_LIST_BRANDS_FILTED = 'GET_LIST_BRANDS_FILTED'
export const SET_CHECKED_BRANDS = 'SET_CHECKED_BRANDS'


// type
export const GET_LIST_ALL_TYPES_SUCCESS = 'GET_LIST_ALL_TYPES_SUCCESS'
export const GET_LIST_ALL_TYPES_ERROR = 'GET_LIST_ALL_TYPES_ERROR'
export const GET_LIST_TYPES_SAGA = 'GET_LIST_TYPES_SAGA'
export const GET_LIST_TYPES_FILTED = 'GET_LIST_TYPES_FILTED'
export const SET_CHECKED_TYPES = 'SET_CHECKED_TYPES'


// price
export const GET_LIST_ALL_PRICES_SUCCESS = 'GET_LIST_ALL_PRICES_SUCCESS'
export const GET_LIST_ALL_PRICES_ERROR = 'GET_LIST_ALL_PRICES_ERROR'
export const GET_LIST_PRICES_SAGA = 'GET_LIST_PRICES_SAGA'
export const GET_LIST_PRICES_FILTED = 'GET_LIST_PRICES_FILTED'
export const SET_VALUES_INPUT_PRICES_GTE = 'SET_VALUES_INPUT_PRICES_GTE'
export const SET_VALUES_INPUT_PRICES_LTE = 'SET_VALUES_INPUT_PRICES_LTE'

// category nef
export const GET_LIST_ALL_CATEGORIES_SUCCESS = 'GET_LIST_ALL_CATEGORIES_SUCCESS'
export const GET_LIST_ALL_CATEGORIES_ERROR = 'GET_LIST_ALL_CATEGORIES_ERROR'
export const GET_LIST_CATEGORIES_SAGA = 'GET_LIST_CATEGORIES_SAGA'
export const GET_LIST_CATEGORIES_FILTED = 'GET_LIST_CATEGORIES_FILTED'
export const SET_SELECTED_CATEGORIES = 'SET_SELECTED_CATEGORIES'

export const SEARCH_ITEM_SAGA = 'SEARCH_ITEM_SAGA'

// search
export const SET_VALUES_INPUT_SEARCH = 'SET_VALUES_INPUT_SEARCH'

// sortby
export const SET_SORT_BY_PRICES = 'SET_SORT_BY_PRICES'